

spring:
  datasource:
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
    url: ${DBMS_CONNECTION:jdbc:mysql://mysqlcontainer-8.0.37:3308/identity}
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /identity

logging:
  level:
    org:
      hibernate:
        engine:
          jdbc:
            spi:
              SqlExceptionHelper: DEBUG
      springframework:
        web: DEBUG

jwt:
  signerKey: 2UTQ8MlOZoMgzvo3uyO2xhVwtBJB6tjj19CtcCZM5ZUPeYA7387Z7L0WrZmqvEo4
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in second
